### ISSUE TITLE
Cyrillic Ы (Yeru) - right stem rendering issue

### ISSUE THREAD

**Issue by vikagrabowska** [googlefonts/roboto-flex#203]
Ы - right stem appears too light or disappears, while in fact its weight is correct. I recently noticed it in opsz 144, but it's worth checking in the rest of design space.

**Comment by dberlow** [comment]
Investigated.  
**soft** has wrong direction and must be corrected by script.

**Comment by dberlow** [comment]
Not seeing this anywhere in the current build.

**Comment by vikagrabowska** [comment]
I can see that while zooming in and out in Acrobat and Drawbot, it might be a rendering issue, but it is only present in Ы, nowhere else. 
<img width="155" alt="image" src="https://user-images.githubusercontent.com/78556166/156630468-a7229699-8a75-4c3e-8941-7a2a246886a8.png">

I'm using a .ttf which was updated 2 days ago. Is this the most current one?
<img width="715" alt="Screenshot 2022-03-03 at 19 35 15" src="https://user-images.githubusercontent.com/78556166/156630016-77e47a90-2134-4986-93a1-b7c1447e2084.png">

**Comment by vikagrabowska** [comment]
I can only see this issue directly in Drawbot. But it is not present in PDFs generated from Drawbot and opened in Acrobat, or when I test the font in TN Type Tools or Dinamo Font Gauntlet. So this is a specifically Drawbot thing and I'm closing an issue.

**Comment by davelab6** [comment]
Thanks @vikagrabowska
