### ISSUE TITLE
k - 144 opsz | 100 wdth | 900 wght

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/roboto-flex#271]
The ascending stem of k seems too wide & therefore dark vs h. IDK if it is a measurable difference or an optical illusion but they don't feel like they match to me.

<img width="511" alt="image" src="https://user-images.githubusercontent.com/2181213/156295364-f2b0f8ee-a7a2-4cbf-b158-ed14831cd406.png">

**Comment by dberlow** [comment]
What do you think we should do, if they are the same measure?

**Comment by davelab6** [comment]
(Despite this issue title saying wght 900, I looked at the opsz 144 wght 1000 master in v3.002 and the measure tool says the `/h` stem is `484` and the `/k` stem is `487`, so not the same measure by 3 units on a 2048 UPM. 

<img width="823" alt="Screen Shot 2022-03-11 at 8 23 10 AM" src="https://user-images.githubusercontent.com/261579/157896422-748c67df-5dc7-48da-a091-3dc33c6b07cf.png">

**Comment by sannorozco** [comment]
Made all this the same, will com on next update.

**Comment by sannorozco** [comment]
I made PR that fix this issue.
