### ISSUE TITLE
Comfort and spacing lc - 100 wght - 8 opsz

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/roboto-flex#286]
On the right, the 400 weight feels comfortable and generous as it should. But that's not going on with the light. The difference is that the one feels relaxing to read and the other does not - or less so. I am not seeing this issue with the 900 wght. This is such a big issue to address in labor terms that I can imagine it being put off. But it still seemed important to address 

I should say that the color in 100 wght is nice and even. That's great.  But the way the color is achieved is the reason for the difference I mentioned above. It is achieved mostly through an interior counter expansion. This emphasis gives the illusion that the type is getting tighter when maybe it is even getting a bit looser or has the same spacing as the 400. However (and this is the rub) the proportional difference between interior shapes and their brightness vs inter letter space generates an illusion that the spaces got tight as it becomes lighter.  

<img width="1161" alt="image" src="https://user-images.githubusercontent.com/2181213/156498393-20861be5-d248-4ec1-8589-5747a6b71e45.png">

**Comment by EbenSorkin** [comment]
I see the problem also in caps but less so. 

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/2181213/156500677-f245ab6f-8c25-401c-bf40-fef4f969a865.png">

**Comment by davelab6** [comment]
I agree that the light feels tight

**Comment by dberlow** [comment]
[#286.pdf](https://github.com/TypeNetwork/Roboto-Flex/files/8178154/286.pdf)

**Comment by dberlow** [comment]
The commit included condensed opsz8 wght100 lowercase bodies on the same units, except for m.

 Live proofing of the previous version is enclosed.
<img width="984" alt="#286 live" src="https://user-images.githubusercontent.com/1956494/156594253-134733a9-5c8d-442c-a3c0-9b768fe9f09d.png">

**Comment by EbenSorkin** [comment]
The sense that the design is the same width in light is also restored.
