### ISSUE TITLE
Slash needs more space! (except at 144 opsz and 400 wght)

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/roboto-flex#298]
Slash needs more space! (except at 144 opsz and 400 wght)

14
<img width="419" alt="image" src="https://user-images.githubusercontent.com/2181213/157124897-dec3e72d-cce7-4448-80b6-5e230ef0e94d.png">
<img width="467" alt="image" src="https://user-images.githubusercontent.com/2181213/157124919-71652cfa-3db7-4c32-9caa-468ead3099b7.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/2181213/157124986-9a415767-7a77-4c3d-b70c-68f69b60e292.png">

8
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2181213/157125066-464b214d-2868-4b30-a160-561a0a55c975.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/2181213/157125092-1b31dd06-cdb7-4c2c-b6a0-f5c76ad87106.png">
<img width="477" alt="image" src="https://user-images.githubusercontent.com/2181213/157125118-504234d7-ea39-4e80-bf6d-51b2cc83503e.png">

144
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/2181213/157125203-64dcc39a-3f59-4903-aea8-1a61cc2a1d1c.png">
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/2181213/157125289-e6a2718e-dc84-4978-ba83-4db13c44b6cd.png">
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/2181213/157125396-e963f4c9-22e8-4929-910b-640dc68cc3f0.png">

Is this spacing or kerning causing the issue?

**Comment by davelab6** [comment]
I think this is a kerning bug, looking at v3.002 at opex 144, the 400 is good but 100 and 1000 in the kern class for /a/e/s there's too much space on the right side of /slash

<img width="1411" alt="Screen Shot 2022-03-11 at 8 11 00 AM" src="https://user-images.githubusercontent.com/261579/157894323-d92055c7-8579-4317-ac01-60461877dac3.png">
<img width="1411" alt="Screen Shot 2022-03-11 at 8 11 04 AM" src="https://user-images.githubusercontent.com/261579/157894327-7467005d-25d9-42c1-98f3-a898938893a1.png">

 

<img width="1411" alt="Screen Shot 2022-03-11 at 8 10 50 AM" src="https://user-images.githubusercontent.com/261579/157894317-c7be1e04-111b-4381-ad1d-08f6ddc4c420.png">

**Comment by sannorozco** [comment]
Updated all this, will come in next update.

**Comment by sp2ed2** [comment]
What happened with this? Still seeing the problem in 2025.
