### ISSUE TITLE
v3.001 Interpolation Issue - Ϗ (03CF) ϗ (03D7)

### ISSUE THREAD

**Issue by kenmcd** [googlefonts/roboto-flex#302]
Appears to be different start points.

![2022-03-09_14-19-12](https://user-images.githubusercontent.com/844920/157548313-c65fd2d7-3644-4092-97e1-c2ab23aff2f3.gif)

**Comment by dberlow** [comment]
RobotoFlex_wght1000
RobotoFlex_opsz14_wght1000_wdth100_GRAD150
repaired and committed.

**Comment by kenmcd** [comment]
v3.002 - Upright is fixed, but slanted is still an issue.

![2022-03-11_12-22-08](https://user-images.githubusercontent.com/844920/157956492-5d3404c9-4a5c-4dc2-8f71-febc0b19a930.gif)

**Comment by dberlow** [comment]
This is fixed and in SO's hands for inclusion.

**Comment by sannorozco** [comment]
Fixed.
