### ISSUE TITLE
Currency - notes and suggestions various axis

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/roboto-flex#312]
14 opsz

This is comparing wght 1000 vs 400 & 100

In the 100 & 400 wght the currency symbols mostly have a similar apparent presence, weight. In the 1000 they don't. 

In the 1000 weight, the dollar sign gets much wider than the S which isn't consistent with the rest of the design. The Euro get's strangely narrow compared to the rest.
The doubled cross bars in yen and Lira and Euro don't match. I think the Euro might be the best standard in this wght.

The vertical bar for cent doesn't match the Dollar and is too light in 1000 wght

The original Euro design doesn't use slightly offset double lines which is more normative. So I can only suggest that we use that model instead of one where they are not. 

The Euro also seems too narrow in 8 opsz and 100 wght

There is also a problem with the dong which doesn't keep a consistent relative width.

The gap in the strokes on Ruble is not like the Lira or the Yen. I suggest that be fixed so it isn't wider or less wide.

<img width="150" alt="image" src="https://user-images.githubusercontent.com/2181213/159138245-a1f661fe-a041-4c60-a3e2-3fa27625c423.png">
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/2181213/159138281-e8b83c26-0b4d-4ea0-b2d3-bc27cf631c95.png">

<img width="128" alt="image" src="https://user-images.githubusercontent.com/2181213/159138256-20514b6f-7bcc-4b36-93d6-cfb6084685e6.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/2181213/159138268-64bfd6ae-4e3f-438e-8ac3-c1fe83d9784e.png">

<img width="131" alt="image" src="https://user-images.githubusercontent.com/2181213/159138375-8600b8da-35c6-4f83-a0c4-a2af657901ff.png">
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/2181213/159138367-d21bff78-cce1-408c-bc38-32495b07c6e9.png">

------------------

8 opsz

in 100 wght the Euro, Lira and Sterling look too narrow. The dong looks too wide and the bar doubly so.

<img width="81" alt="image" src="https://user-images.githubusercontent.com/2181213/159138725-677ebb3a-be2f-40c2-a52d-d14188a68817.png">
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/2181213/159138773-8abb54a3-1801-49d5-a25c-3f4b42b18815.png">
<img width="249" alt="image" src="https://user-images.githubusercontent.com/2181213/159138844-fb080fd4-4b9d-4342-aece-d269284211fa.png">

400 wght -  

 dong stroke is too wide

<img width="160" alt="image" src="https://user-images.githubusercontent.com/2181213/159138888-26890c04-81f0-4bb2-9895-12ef22b67d99.png">
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/2181213/159138870-911a9f0a-de8a-45c9-88cf-cc09b19c1cfb.png">

1000 wght - 
As with 14 opsz The doubled cross bars in yen and Lira and Euro don't match. I think the Euro might be the best standard in this wght.

The vertical bar for cent doesn't match the Dollar and is too light in 1000 wght

<img width="161" alt="image" src="https://user-images.githubusercontent.com/2181213/159138929-18a4fd15-0d2f-4de2-aea4-d9acb8bf047d.png">
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/2181213/159138962-d4c39db1-7819-427b-8c24-d128ad0739a2.png">

**Comment by EbenSorkin** [comment]
144 opsz

1000 wght

dong bar too narrow
Euro and Sterling much less present than Dollar.
Top and bottom stroke of cent and dollar don't match. Something closer to cent might be better.
Sterling and Lira - the bend in the vertical stroke that's so important to identifying these is hard to see. Narrower bars might help but revisiting the curve might be valuable too.
The doubled strokes don't match ( Yen & Euro & Lira )
Left side of horizontal strokes are getting a bit too small
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/2181213/159146164-8ac6afbe-d4fe-4a8c-bd9b-acf48d714192.png">

400 wght 
The doubled strokes don't match ( Yen & Euro & Lira ) - it is more subtle but still... In this case the Lira strokes seem too heavy vs the others.
Top and bottom stroke of cent and dollar don't match. Something between cent and dollar might be better.
I'd like the upper right drooping terminal in Stirling and Lira to be slightly heavier. I think it would pull the shape together. Something like what we see in the Dollar would be good.
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/2181213/159146197-1c1f22ce-47fc-4be4-a41d-6a9b2d635242.png">

100 wght
The bends in the vertical stroke Sterling and Lira seem dull.
The character of the curve in Euro doesn't seem to match the rest of the design.
The horizontal bars may be 1 unit too thick - see Yen and Euro
The upper left and lower right of dollar seem a bit to thin
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/2181213/159146285-e52e68e8-ef37-4c61-be9b-81166d4dadea.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/2181213/159146337-e2f11559-856a-4958-80bc-6e30cdc52c54.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/2181213/159146371-c7b3cc40-3ee9-40ce-bc5d-4c9e1e518ffa.png">

**Comment by sannorozco** [comment]
Applied some suggestions.
