### ISSUE TITLE
`dotaccent` has no relation to `i`

### ISSUE THREAD

**Issue by twardoch** [googlefonts/roboto-flex#313]
The `dotaccent` mark used in glyphs like `zdotaccent` has no relation in shape to the dot over `i`, and is too small. 

The dots used in `dieresis` are normally smaller than the dot over `i`. But the `dotaccent` mark should always have the same form as the `i` dot, though it may be positioned slightly lower over letters like `z` or `o` than it is over `i`. When I write the word `niżby`, both dots should look the same, though their vertical position may differ. 

https://user-images.githubusercontent.com/519108/159824028-36849b38-94ea-4247-8edd-bcc98d650204.mp4

**Comment by sannorozco** [comment]
Updated, in wght1000 locations could’t be as big as lc /i, because overshot in round shapes.

**Comment by davelab6** [comment]
@twardoch is this resolved as you expect?
