### ISSUE TITLE
`YTAS` axis changes the `i` dot position until a clash, but does not change any marks

### ISSUE THREAD

**Issue by twardoch** [googlefonts/roboto-flex#314]
The `YTAS` axis should either leave the vertical position of marks in glyphs like `aacute`, `odieresis` etc. alone, and then it should also leave the position of the `i` dot alone, or it should adjust the positions of all marks (including the `i` dot, and of course `j` dot). If you adjust the position, the in blackest masters, the shape of the marks (including the `i` dot) should become vertically compressed if the `YTAS` value is <720 or so.

https://user-images.githubusercontent.com/519108/159824028-36849b38-94ea-4247-8edd-bcc98d650204.mp4

**Comment by davelab6** [comment]
@dbelrow how large of a change is this to execute?

**Comment by twardoch** [comment]
BTW, I don’t really expect my PR https://github.com/googlefonts/roboto-flex/pull/320 to be merged as is. I’d prefer a more comprehensive, designer-led solution. :)

**Comment by davelab6** [comment]
@sannorozco whats the status of this

**Comment by davelab6** [comment]
@sannorozco please update us

**Comment by sannorozco** [comment]
Yes, in the latest version YTAS does not shifts any mark or dot, this is fixed.

**Comment by davelab6** [comment]
Do we then need a YTDH (Y Transparent Diacritic Height) axis to control dot
of i and other mark positions?

**Comment by davelab6** [comment]
This maybe a question for @dberlow
