### ISSUE TITLE
`k` in `XTRA` axis | opsz 48

### ISSUE THREAD

**Issue by twardoch** [googlefonts/roboto-flex#317]
The `k` glyph in the `XTRA` axis has very visible problems in the diagonal arms, not present in other diagonal glyphs, especially around `opsz` 48.

https://user-images.githubusercontent.com/519108/159830639-aa012e1c-8ee3-4b6a-9057-97f3b4dc88dd.mp4

```
.my-text {
	font-feature-settings: "rvrn" 1;
	font-variation-settings: "wght" 400, "wdth" 115.81360483329604, "opsz" 144, "GRAD" 0, "slnt" 0, "XTRA" 603, "XOPQ" 96, "YOPQ" 79, "YTLC" 514, "YTUC" 712, "YTAS" 750, "YTDE" -203, "YTFI" 738;
}
```
<img width="1536" alt="scr- 2022-03-24 at 03 33 26" src="https://user-images.githubusercontent.com/519108/159830617-16543dbf-ec53-48b3-bf4c-b1c778a1a1f5.png">

**Comment by davelab6** [comment]
@dberlow please take a look

**Comment by dberlow** [comment]
I can see. At 115% width, if you absolutely slam XRTA to the max, some glyphs are breaking.
We have supplied a safe 35% wider in the wdth axis if Adam needs it.

I think we’ve demonstrated the uses of this axis, and it’s not any more for the achievement of other widths, than grade is for the achievement of other weights. If someone wants to shrink or grow a column width, they should use width. If they want to shrink or grow a line they should use XTRA.

Or, if we are planning To make the parametric space safe for children, let me know and we’ll start trimming the ranges and adding septovars, heptovars and centovars.

**Comment by twardoch** [comment]
@dberlow In general, I think there’s a differerence: 

1. If a param axis extreme **generally** (in many glyphs) produces unreasonable results in some combinations of other axes, then there’s not point to "fix" — we simply designate that are "not safe for children". 

2. If a param axis extreme produces bad results in only a handful of glyphs in some combos of other axes, while **most** glyphs are more-less fine — in such a case, we could consider making that area "safe for children", so perhaps it’d be worth fixing the glyphs in question. 

Realistically, there are **common** ("important") glyphs and there are less-important glyphs. I think if one basic letter out of the set of basic letters fails, then perhaps it’s worth considering fixing. 

We could have an analogy to fitting: 

1. The general rules are sidebearings, and they drive the spacing of any pairs. 
2. If we find that some pairs of certain groups/classes don’t perform well with just sidebearings, we use class kerning. 
3. If we find that class kerning does not perform well in certain individual pairs, we use kerning exceptions. 

We could see this approach as "progressive fixing" of the fitting. 

Additive delta design is a similar case. You have the neutral master, and you put deltas for width in one direction, and you put deltas for weight in another direction. Then you look at the result of their addition — and you fix what needs for fixing. With more axes, there is more automatic addition, but also in some cases the problems manifest themselves less and less, but they still show in a few glyphs (often diagonals). 

With kerning, you may choose to stop at some point, or you may continue. I guess with "important" (common) glyph pairs, it’s reasonable to continue for a bit longer, while with rare combinations you can give up earlier. With very common but problematic combos, one can even do kerning triplets etc. 

Would you agree in principle? That’s how I’ve interpreted your approach to Flex :) 

Does the UFO workflow you use allow for partial master fixes? (Let’s image some septovar would be added only for 1 glyph or a handful of glyphs). 

Not saying this **has** to be done — but I’d love to see a "cost/benefit" analysis of making THOSE corners safe for children which are now ALMOST safe for children. Of course those corners that are internally labeled "hic sunt dracones" — we should leave them be :D

**Comment by davelab6** [comment]
The multiple angles of `k` make it likely to suffer when others are ok. But the `K` and other diagonals shown in the samples above are working, which suggests that this one glyph is feasible to fix. 

My understanding of why parametric axes have the reach they do, is to do with the fact that in ot1.8-1.9, there is no way to relate axes to each other, so the range that makes sense for XTRA to reach wider at the minimum width, opsz max, weight min (the most narrow part of the primary design space) doesn't make sense at wider parts, but there's no way to trim it as you move away from there in weight width optical size.

It also occurs to me that it may be that HOI could help fix diagonals in these situations, by truly rotating the angles.

**Comment by davelab6** [comment]
@sannorozco PTAL

**Comment by sannorozco** [comment]
Yes, this was fixed in yesterday’s update, here’s the same location.

<img width="1820" alt="Screen Shot 2022-05-04 at 4 48 52 PM" src="https://user-images.githubusercontent.com/1184152/166831433-bf87de7b-5dcc-4628-ab7f-697329b93e78.png">
