### ISSUE TITLE
Apply new designspace labelname values to all axes

### ISSUE THREAD

**Issue by davelab6** [googlefonts/roboto-flex#335]
Please add full `labelname` values based on the axis names in https://github.com/google/fonts/tree/main/cc-by-sa/knowledge/glossary/terms/ `*_axis/`

eg in your [designspace](https://github.com/googlefonts/roboto-flex/blob/21a94eabbe824db4e7b583a744971fc39ee5b1dd/sources/RobotoFlex.designspace#L5 
) change

    <labelname xml:lang="en">wght</labelname> 

to 

    <labelname xml:lang="en">Weight</labelname> 

based on `fonts/cc-by-sa/knowledge/glossary/terms/weight_axisterm.textproto`

    name: "Weight axis (wght)"

[:-12]

Please PR and assign to me for review :)

**Comment by sannorozco** [comment]
@davelab6 PR ready for your review.

**Comment by sannorozco** [comment]
This as been implemented.

**Comment by davelab6** [comment]
DS XML Looks good thanks!
