### ISSUE TITLE
Wrong Cyrillic contrast | YOPQ 25, 135

### ISSUE THREAD

**Issue by ravid29** [googlefonts/roboto-flex#352]
i noticed some cyrillic contrast errors and want you to fix them :)

YOPQ: 25
![Web 1920 – 1](https://user-images.githubusercontent.com/78262241/167648288-45c16f00-1245-4f95-9e28-87121a4da150.png)

YOPQ: 135
![Web 1920 – 2](https://user-images.githubusercontent.com/78262241/167648329-62abd642-f2b6-493f-ae0f-3708af4d7b55.png)

**Comment by davelab6** [comment]
@ravid29 thanks! Font Bureau have already been working to address this.

**Comment by davelab6** [comment]
Closing as tracking in #354
