### ISSUE TITLE
Is there any plan to provide "Roboto Flex Mono" for coding users?

### ISSUE THREAD

**Issue by dantezhu** [googlefonts/roboto-flex#357]
Thanks very much!

**Comment by dberlow** [comment]
It’s in there somewhere. Do you want to code a code font?

**Comment by dantezhu** [comment]
@dberlow yes, I really want it. Roboto mono's `$` is not handled very well, and it is difficult to distinguish it from `S`. I see that roboto flex has modified the display of `$`. If a roboto flex mono is directly released, it will be very popular. .

**Comment by davelab6** [comment]
>> It’s in there somewhere. Do you want to code a code font?
>
> yes, I really want it

My interpretation of David's [elliptical](https://www.google.com/search?q=elliptical+definition) statement is that it is possible to write code (javascript for a browser, or whatever your typesetting engine's scripting language is) to configure the parametric axes on a character by character basis (and maybe optimize via character classes, ie sets of equal advance widths) to produce monospace typesetting without additional font development.

This would be similar to @lorp 's https://github.com/Lorp/fit-to-width and I believe he and @twardoch were recently discussing a font editor script that would auto-mono'ize a typeface with Width or XTRA axes.

**Comment by davelab6** [comment]
As the lead operations manager for Google Fonts, I can officially state that no, there are no current plans to provide a Roboto Flex Mono for coding users. 

>> It’s in there somewhere. Do you want to code a code font?
>
> yes, I really want it

My interpretation of David's [elliptical](https://www.google.com/search?q=elliptical+definition) statement is that it is possible to write code (javascript for a browser, or whatever your typesetting engine's scripting language is) to configure the parametric axes on a character by character basis (and maybe optimize via character classes, ie sets of equal advance widths) to produce monospace typesetting without additional font development.

This would be similar to @lorp 's https://github.com/Lorp/fit-to-width and I believe he and @twardoch were recently discussing a font editor script that would auto-mono'ize a typeface with Width or XTRA axes.

You'd use something like https://github.com/Lorp/samsa or https://github.com/foliojs/fontkit to get the advance widths of all the characters, and then set a target advance width, then for each character iterate over an axis that changes advance widths until it hits the target advance width, possibly using bisecting or some other (sort?) algorithm to make it fast; then classify/deduplicate the dictionary of original advance widths to axis values to match the target, and make each of those classes into CSS classes; then iterate over the HTML and wrap each character in a span with the relevant class.

I'd also look at the work @graphicore is doing with @dberlow in https://github.com/graphicore/varla-varfo to see similar stuff.

**Comment by Lorp** [comment]
Setting parameters glyph-by-glyph has been on my mind for a while for monospace and other purposes. Roboto Flex is not ready currently, but with the addition of a spacing axis to adjust sidebearings, an initial monospace instance could be produced by choosing a uniform glyph width and an XOPQ setting, then for each glyph adjusting XTRA and the spacing axis until it fits, with some heuristic to choose which of many solutions to choose. The heuristic might also request a reduced XOPQ in wide glyphs such as ‘M’ and ‘W’ to avoid pushing XTRA and the spacing axis beyond aesthetic limits. Of course, a real monospace font would probably need numerous adjustments, notably for glyphs that XTRA doesn’t affect (e.g. ‘i’ and ‘l’), such as adding variable-length serifs.

**Comment by dantezhu** [comment]
Thanks very much. @davelab6 @Lorp
