### ISSUE TITLE
Contrast and design flaws

### ISSUE THREAD

**Issue by 832Co** [googlefonts/roboto-flex#368]
the Roboto font will seem to have been initially upgraded into Roboto Flex, but it was completely ruined by contrast inconsistencies.

some letters are not designed in low contrasts. in bolder weights, the letter U is correctly low contrast, but the rest of them like A, K, M, V, and W are not and are like serifs with high contrast even if it's in low optical size, and note that I don't want to use and I'm not used in the YOPQ to tweak thin strokes anymore in general.
![image](https://user-images.githubusercontent.com/115700870/195570217-3aa2bfe0-0d40-4a8d-86f1-3afc23c04d08.png)
![image](https://user-images.githubusercontent.com/115700870/195570269-f4fd241e-7100-4177-ae04-43b1fa28118c.png)
Plus, letters with Vietnamese diacritics are too tight to fit into the text without complete line spacing tweaks.
![image](https://user-images.githubusercontent.com/115700870/195573631-c458d67f-efcf-4e22-9676-52ccf7a1343a.png)
The micro sign looks incorrectly italicized even with italics.
![image](https://user-images.githubusercontent.com/115700870/195572448-b1d3dacb-9e84-4e36-9dd8-8596e8de3198.png)
![image](https://user-images.githubusercontent.com/115700870/195572569-3cf2850f-1719-46a4-b6d7-c761a16d91fa.png)

**Comment by dberlow** [comment]
Do you plan to use the 18point size in all caps at 86 point a lot?

Should the additional height of Vietnamese diacritics demand we scale the whole font smaller than the previous versions of Roboto to fit the diacritics within default line spacing? Also not sure what "complete line spacing tweaks" would mean other than increasing the linespacing when using Vietnamese more than when using other Eurasian languages with diacritics?

The mirco's correct italicization would do what differently?

Thanks for your comments.

**Comment by 832Co** [comment]
I would like to expect the correct low-contrast strokes like this:
![195570269-f4fd241e-7100-4177-ae04-43b1fa28118c-Recovered](https://user-images.githubusercontent.com/115700870/195614251-b33187aa-e822-4dd2-9b44-5b655fcf2d74.png)
I also noticed that the Latin letter schwa looks too different from the Cyrillic one. the Cyrillic letter schwa should be equivalent to the Latin one.
![image](https://user-images.githubusercontent.com/115700870/195614546-9ffe5673-1ec3-4868-a94b-3a88bbb6c836.png)

**Comment by ilyaruderman** [comment]
Hi everyone,
I just want to comment on Cyrillic Schwa here: shortly, NO, it shouldn't be
identical to the Latin one. Could be in theory, but it's totally correctly
drawn and can have a different design — no harm here.
thanks
Ilya
