### ISSUE TITLE
Roboto Flex as static font

### ISSUE THREAD

**Issue by yceballost** [googlefonts/roboto-flex#370]
Hi guys

Thanks for this typography, it is great!

Is it possible to get the static fonts of Roboto Flex?

In our product, we don't need to include an extra space including the rest of the weights

I saw [fonttools](https://fonttools.readthedocs.io/en/latest/varLib/instancer.html) with the possibility to split variable fonts but would be better if the original source of Roboto include this possibility to avoid errors in conversion

**Comment by davelab6** [comment]
Use the Slicer tool to generate static fonts. https://slice-gui.netlify.app/
